name: Publish

on: 
  release:
    types: [published]

jobs:
  publish:
    name: Publish Package to PyPI and Test PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pypa/build
      run: >-
        python -m
        pip install --upgrade build
    - name: Build a binary wheel and a source tarball
      run: python -m build
    - name: Publish distribution to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        verbose: true
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - name: Publish distribution to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        verbose: true
        password: ${{ secrets.PYPI_API_TOKEN }}
